
language: node_js
node_js:
  - lts/*
cache: yarn

git:
  depth: 1

branches: 
  only: 
    - master
    - dev

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - openssl aes-256-cbc -K $encrypted_40be4da7d498_key -iv $encrypted_40be4da7d498_iv -in id_rsa_lataio.enc -out ~/.ssh/id_rsa_lataio -d
  - chmod 600 ~/.ssh/id_rsa_lataio
  - echo -e "Host 106.14.156.134\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa_lataio" >> ~/.ssh/config
  # addons:
  #  ssh_known_hosts: buzhifangxue.com

install:
  - yarn

script: 
  - yarn build

after_success:
  - bash publish.sh
  # - cd build
  # - ls -a
  # - scp -o stricthostkeychecking=no  -r ./* root@106.14.156.134:/www/buzhi

# deploy:
#   provider: script
#   script: bash deploy.sh
#   on:
#     branch: master