language: node_js
node_js:
  - lts/*
cache: yarn

branches: 
  only: 
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script: 
  - yarn build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master